name: Build and Release DMX Receiver Sketches

on:
  workflow_dispatch:
    inputs:
      led_count:
        description: "Number of LEDs"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dmx_start: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v4

      # Build RGB version
      - name: Prepare RGB sketch for DMX start ${{ matrix.dmx_start }}
        run: |
          cp ws281x-dmx-controller/receiver_rgb/receiver_rgb.ino ws281x-dmx-controller/receiver_rgb/receiver_rgb_${{ matrix.dmx_start }}.ino
          sed -i "s/<#NUMPIXELS#>/${{ github.event.inputs.led_count }}/g" ws281x-dmx-controller/receiver_rgb/receiver_rgb_${{ matrix.dmx_start }}.ino
          sed -i "s/<#DMXADDRESS#>/${{ matrix.dmx_start }}/g" ws281x-dmx-controller/receiver_rgb/receiver_rgb_${{ matrix.dmx_start }}.ino

      - name: Compile RGB sketch for DMX start ${{ matrix.dmx_start }}
        uses: arduino/compile-sketches@v1.3.0
        with:
          sketch-path: ws281x-dmx-controller/receiver_rgb
          fqbn: arduino:avr:uno
          libraries: |
            DMXSerial
          build-properties: |
            sketch=receiver_rgb${{ matrix.dmx_start }}.ino

      - name: Rename RGB output binary
        run: |
          mv ws281x-dmx-controller/receiver_rgb/build/receiver_rgb_${{ matrix.dmx_start }}.ino.hex \
             ws281x-dmx-controller/receiver_rgb/build/receiver_rgb_${{ matrix.dmx_start }}_${{ github.event.inputs.led_count }}leds.hex
      - name: Upload RGB build artifact for DMX start ${{ matrix.dmx_start }}
        uses: actions/upload-artifact@v4
        with:
          name: receiver_rgb_${{ matrix.dmx_start }}_${{ github.event.inputs.led_count }}
          path: ws281x-dmx-controller/receiver_rgb/build/receiver_rgb_${{ matrix.dmx_start }}_${{ github.event.inputs.led_count }}.hex

      # Build RGBW version
      - name: Prepare RGBW sketch for DMX start ${{ matrix.dmx_start }}
        run: |
          cp ws281x-dmx-controller/receiver_rgbw/receiver_rgbw.ino ws281x-dmx-controller/receiver_rgbw/receiver_rgbw_${{ matrix.dmx_start }}.ino
          sed -i "s/<#NUMPIXELS#>/${{ github.event.inputs.led_count }}/g" ws281x-dmx-controller/receiver_rgbw/receiver_rgbw_${{ matrix.dmx_start }}.ino
          sed -i "s/<#DMXADDRESS#>/${{ matrix.dmx_start }}/g" ws281x-dmx-controller/receiver_rgbw/receiver_rgbw_${{ matrix.dmx_start }}.ino

      - name: Compile RGBW sketch for DMX start ${{ matrix.dmx_start }}
        uses: arduino/compile-sketches@v1.3.0
        with:
          sketch-path: ws281x-dmx-controller/receiver_rgbw
          fqbn: arduino:avr:uno
          libraries: |
            DMXSerial
          build-properties: |
            sketch=receiver_rgbw_${{ matrix.dmx_start }}.ino

      - name: Rename RGBW output binary
        run: |
          mv ws281x-dmx-controller/receiver_rgbw/build/receiver_rgbw_${{ matrix.dmx_start }}.ino.hex \
             ws281x-dmx-controller/receiver_rgbw/build/receiver_rgbw_${{ matrix.dmx_start }}_${{ github.event.inputs.led_count }}leds.hex
      - name: Upload RGBW build artifact for DMX start ${{ matrix.dmx_start }}
        uses: actions/upload-artifact@v4
        with:
          name: receiver_rgbw_${{ matrix.dmx_start }}_${{ github.event.inputs.led_count }}
          path: ws281x-dmx-controller/receiver_rgbw/build/receiver_rgbw_${{ matrix.dmx_start }}_${{ github.event.inputs.led_count }}.hex

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all RGB build artifacts
        uses: actions/download-artifact@v4
        with:
          path: rgb_builds

      - name: Download all RGBW build artifacts
        uses: actions/download-artifact@v4
        with:
          path: rgbw_builds

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.led_count }}
          name: "DMX Receiver Builds for ${{ github.event.inputs.led_count }} LEDs"
          files: |
            rgb_builds/receiver_rgb_*_${{ github.event.inputs.led_count }}.hex
            rgbw_builds/receiver_rgbw_*_${{ github.event.inputs.led_count }}.hex
